name: assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - expat=2.7.1=h313beb8_0
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - icu=75.1=hfee45f7_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h92dc006_1
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.4=h4a912ad_0
  - matplotlib=3.10.7=py310hb6292c7_0
  - matplotlib-base=3.10.7=py310h0181960_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h0b18652_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - statsmodels=0.14.5=py310hfdc7867_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py310h7bdd564_1
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310h7bdd564_1
  - wheel=0.45.1=py310hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - absl-py==2.3.1
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.9.23
      - fqdn==1.5.1
      - gast==0.6.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - keras==2.15.0
      - lark==1.3.1
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - ml-dtypes==0.2.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - split-folders==0.5.1
      - stack-data==0.6.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.15.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: /opt/anaconda3/envs/assessment
